---

- name: Azure Ubuntu VM
  hosts: localhost
  connection: local
  tasks:
    - name: Dynamic Public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ rg_name }}"
        allocation_method: Dynamic
        name: "{{ pubip_name }}"

    - name: VNIC
      azure_rm_networkinterface:
        resource_group: "{{ rg_name }}"
        name: "{{ vnic_name }}"
        private_ip_allocation_method: Static
        private_ip_address: "{{ priv_ip }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ pubip_name }}"
        security_group: "{{ nsg_name }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ rg_name }}"
        name: "{{ vm_name }}"
        vm_size: Standard_A1_v2
        managed_disk_type: Standard_LRS
        admin_username: guilbert
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: /home/guilbert/.ssh/authorized_keys
            key_data: "ssh-rsa key"
        network_interfaces: "{{ vnic_name }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest

    - name: Poweroff VM
      azure_rm_virtualmachine:
        resource_group: "{{ rg_name }}"
        name: "{{ vm_name }}"
        started: no

    - name: Deallocate VM
      azure_rm_virtualmachine:
        resource_group: "{{ rg_name }}"
        name: "{{ vm_name }}"
        allocated: no
