- name: Delete Azure Resource Group via Ansible
  hosts: localhost
  connection: local
  tasks:
  - name: Delete a resource group
    azure_rm_resourcegroup:
      name: "{{ rg_name }}"
      state: absent
      force: yes